In [2]:
!pip install torch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 10.4 MB/s eta 0:00:0000:0100:01
  Using cached nvidia_cusolver_cu11-11.4.0.1-2-py3-none-manylinux1_x86_64.whl (102.6 MB)
  Using cached nvidia_curand_cu11-10.2.10.91-py3-none-manylinux1_x86_64.whl (54.6 MB)
  Using cached nvidia_cublas_cu11-11.10.3.66-py3-none-manylinux1_x86_64.whl (317.1 MB)
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
  Using cached triton-2.0.0-1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (63.3 MB)
  Using cached filelock-3.12.0-py3-none-any.whl (10 kB)
  Using cached nvidia_cuda_cupti_cu11-11.7.101-py3-none-manylinux1_x86_64.whl (11.8 MB)
  Using cached nvidia_cufft_cu11-10.9.0.58-py3-none-manylinux1_x86_64.whl (168.4 MB)
  Using cached nvidia_cusparse_cu11-11.7.4.91-py3-none-manylinux1_x86_64.whl (173.2 MB)
  Using cached nvidia_nvtx_cu11-11.7.91-py3-none-manylinux1_x86_64.whl (98 kB)
  Using cached nvidia_cuda_runtime_cu11-11.7.99-py3-none-manylinux1_x86_64.whl (849 kB)
  Using ca

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

# Define the neural network architecture for the encoder
class Encoder(nn.Module):
    def __init__(self, num_features, num_components):
        super(Encoder, self).__init__()
        self.fc = nn.Linear(num_features, num_components)

    def forward(self, x):
        output = self.fc(x)
        return output

# Prepare the input and output data
# Assuming you have Y (input data) and X (expected output) as NumPy arrays
Y = np.random.rand(100, 20)  # Example input data (100 samples, 20 features)
X = np.random.rand(100, 5)   # Example expected output (100 samples, 5 components)

# Convert the data to PyTorch tensors
Y_tensor = torch.tensor(Y, dtype=torch.float32)
X_tensor = torch.tensor(X, dtype=torch.float32)

# Define the configuration (similar to cfg dictionary in the provided code)
cfg = {
    'gamma': 0.1,
    'returnPattern': False,
    'demean': True
}

# Train the encoder
num_features = Y.shape[1]
num_components = X.shape[1]

# Create an instance of the Encoder network
encoder = Encoder(num_features, num_components)

# Define the loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(encoder.parameters(), lr=0.01)

# Training loop
num_epochs = 1000
for epoch in range(num_epochs):
    # Forward pass
    outputs = encoder(Y_tensor)

    # Compute the loss
    loss = criterion(outputs, X_tensor)

    # Backward and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Print the loss for monitoring the training progress
    if (epoch+1) % 100 == 0:
        print(f'Epoch: {epoch+1}/{num_epochs}, Loss: {loss.item()}')

# Access the learned weights of the encoder
encoder_weights = encoder.fc.weight.detach().numpy()

# Access the learned patterns (if required)
if cfg['returnPattern']:
    encoder_patterns = encoder_weights.T  # Transpose the weight matrix if necessary



Epoch: 100/1000, Loss: 0.11548864096403122
Epoch: 200/1000, Loss: 0.11048425734043121
Epoch: 300/1000, Loss: 0.10723289847373962
Epoch: 400/1000, Loss: 0.10425393283367157
Epoch: 500/1000, Loss: 0.10151467472314835
Epoch: 600/1000, Loss: 0.09899371862411499
Epoch: 700/1000, Loss: 0.09667181223630905
Epoch: 800/1000, Loss: 0.09453147649765015
Epoch: 900/1000, Loss: 0.092556893825531
Epoch: 1000/1000, Loss: 0.09073369950056076


In [9]:
new_data = np.random.rand(100, 20)
new_data_tensor = torch.tensor(new_data, dtype=torch.float32)
encoded_output = encoder(new_data_tensor).detach().numpy()



In [13]:
print(new_data.shape)
print(new_data)

(100, 20)
[[0.07627269 0.55635642 0.50809574 ... 0.00362764 0.36955551 0.4265542 ]
 [0.81776772 0.48315676 0.133133   ... 0.3152899  0.42362307 0.97148497]
 [0.03306886 0.34173603 0.76609811 ... 0.68346859 0.17852321 0.45351997]
 ...
 [0.49954603 0.26662369 0.91547228 ... 0.20801754 0.57939769 0.33875207]
 [0.19761672 0.03520723 0.75738913 ... 0.73528241 0.52568895 0.15009357]
 [0.70860156 0.06271984 0.80692653 ... 0.01502953 0.94324721 0.39612645]]


In [15]:
encoded_output.shape
print(encoded_output)

[[0.6597467  0.6025914  0.8249438  0.43570042 0.7246838 ]
 [0.3483673  0.4422352  0.33449763 0.7574107  0.21726435]
 [0.399386   0.36747652 0.41357148 0.5511156  0.32902807]
 [0.48720127 0.5554147  0.75285846 0.51367515 0.48262638]
 [0.58317345 0.5364338  0.70479494 0.70570993 0.5792106 ]
 [0.48714116 0.5002279  0.50343275 0.5767022  0.37495872]
 [0.62825197 0.48519695 0.1948639  0.33512163 0.29832935]
 [0.9774969  0.4512077  0.40989625 0.67284936 0.38486385]
 [0.68472224 0.54990464 0.6280487  0.48447376 0.48439556]
 [0.4271128  0.39516115 0.4694422  0.4509844  0.30254745]
 [0.4919806  0.52435994 0.70568174 0.59124166 0.6220854 ]
 [0.57235366 0.4323614  0.45119953 0.48169506 0.34668344]
 [0.4412004  0.43112126 0.49552327 0.41809094 0.5053555 ]
 [0.41655818 0.26287305 0.20786095 0.4033131  0.30010697]
 [0.40050176 0.38480565 0.24292482 0.51762146 0.1934618 ]
 [0.43261978 0.2417041  0.45136803 0.52725464 0.25675115]
 [0.5595094  0.3004853  0.3798677  0.37706771 0.4537416 ]
 [0.58798975 0